# Generated by Django 5.1.4 on 2025-01-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_app_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='points',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
